include $(GNUSTEP_MAKEFILES)/common.make

BUNDLE_NAME = Cddb
BUNDLE_EXTENSION = .bundle

Cddb_RESOURCE_FILES =

Cddb_OBJC_FILES = Cddb.m

Cddb_HEADERS = Cddb.h

Cddb_PRINCIPAL_CLASS = Cddb

Cddb_HEADER_FILES = Cddb.h
Cddb_HEADER_FILES_DIR = .
Cddb_HEADER_FILES_INSTALL_DIR = Cddb

ADDITIONAL_OBJCFLAGS = -Wall

ADDITIONAL_INCLUDE_DIRS += -I..

-include GNUmakefile.preable

include $(GNUSTEP_MAKEFILES)/bundle.make

-include GNUmakefile.postamble
